/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.CardLayout;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class ejercicio_2 extends javax.swing.JFrame {
private JFrame parentFrame;
    /**
     * Creates new form ejercicio_2
     */
    public ejercicio_2() {
        initComponents();
    }
  // Constructor que recibe un JFrame
    public ejercicio_2(JFrame frame) {
        this.parentFrame = frame; // Asigna el JFrame recibido a la variable
        initComponents(); // Inicializa los componentes de la interfaz
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op = new javax.swing.JPanel();
        usuarioTextfield = new javax.swing.JTextField();
        Button1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        contrasenaPassword = new javax.swing.JPasswordField();
        mensajeWelcome = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        op.setBackground(new java.awt.Color(204, 204, 255));
        op.setForeground(new java.awt.Color(255, 255, 255));

        usuarioTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextfieldActionPerformed(evt);
            }
        });

        Button1.setForeground(new java.awt.Color(0, 204, 51));
        Button1.setText("Login");
        Button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("                  bienvenido");

        mensajeWelcome.setForeground(new java.awt.Color(204, 204, 255));

        labelContraseña.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(0, 0, 204));
        labelContraseña.setText("Contraseña");

        labelUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(51, 51, 255));
        labelUsuario.setText("Usuario");

        javax.swing.GroupLayout opLayout = new javax.swing.GroupLayout(op);
        op.setLayout(opLayout);
        opLayout.setHorizontalGroup(
            opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opLayout.createSequentialGroup()
                .addGroup(opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(mensajeWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(opLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(opLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contrasenaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(opLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(Button1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        opLayout.setVerticalGroup(
            opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addComponent(labelUsuario)
                .addGap(18, 18, 18)
                .addComponent(usuarioTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contrasenaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(mensajeWelcome)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(op, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextfieldActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
String Usuario="poveda1318";
String Contrasena="1318";
String mensaje="bienvenido";
String usuarioTeclado=usuarioTextfield.getText();
String contrasenaIngresada= new String(contrasenaPassword.getPassword());
if(usuarioTeclado.equals(Usuario)&& contrasenaIngresada.equals(Contrasena)){
    JOptionPane.showMessageDialog(null,mensaje);
     mensajeWelcome.setText(mensaje);
    
    if(parentFrame !=null){
    parentFrame.dispose();
    }
    this.dispose();

    
    
}else{
    JOptionPane.showMessageDialog(null, "usuario o contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
}
// TODO add your handling code here:
    }//GEN-LAST:event_Button1ActionPerformed
 public JPanel getOp() {
        return op;
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JPasswordField contrasenaPassword;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel mensajeWelcome;
    private javax.swing.JPanel op;
    private javax.swing.JTextField usuarioTextfield;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return Button1;
    }

   



}

