
package Interfaces;

import java.util.ArrayList;
import POO.GestionMenu;
import POO.GestionDeRestaurante;
import javax.swing.DefaultListModel;

/**
 *
 * @author USUARIO
 */
public class ventanaMenu extends javax.swing.JFrame {
    public ArrayList<GestionMenu> lista;
    public GestionDeRestaurante ver;
    
    DefaultListModel<String> modelo=new DefaultListModel<>();
    /**
     * Creates new form ventanaMenu
     * @param lista
     */
  public ventanaMenu(ArrayList<GestionMenu> lista) {
    initComponents(); // Inicializa los componentes gráficos
    this.lista = lista; // Asigna la lista pasada como parámetro
    this.modelo = new DefaultListModel<>(); // Inicializa el modelo de la lista
    jListArryslist.setModel(modelo); // Asigna el modelo al JList
    setLocationRelativeTo(null); // Centra la ventana en la pantalla
    mostrarEnJList(); // Llena el JList con los datos de la lista
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArryslist = new javax.swing.JList<>();
        buttonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jListArryslist.setBackground(new java.awt.Color(153, 153, 255));
        jListArryslist.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jListArryslist.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jListArryslist.setForeground(new java.awt.Color(255, 0, 0));
        jListArryslist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListArryslist.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jListArryslistAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jListArryslist);

        buttonAtras.setText("back");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAtras))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonAtras)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jListArryslistAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jListArryslistAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jListArryslistAncestorMoved
  private void mostrarEnJList() {
        modelo.clear(); // Limpiamos el modelo antes de agregar nuevos elementos
        for (GestionMenu plato : lista) {
            modelo.addElement(plato.getNombrePlato()+ " - $" + plato.getPrecio()); // Mostramos el nombre y precio
        }
  }
        
    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
this.dispose();
ventana2 ver=new ventana2();
ver.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_buttonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtras;
    private javax.swing.JList<String> jListArryslist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
